using NUnit.Framework;
using UnityEditor;
using UnityEngine;

public class PlayerHumanoidIntegrationTests
{
    private const string PlayerModelPath = "Assets/Ch01_nonPBR@Double Dagger Stab.fbx";

    private static readonly HumanBodyBones[] EssentialBones =
    {
        HumanBodyBones.Hips,
        HumanBodyBones.Spine,
        HumanBodyBones.Head,
        HumanBodyBones.LeftUpperArm,
        HumanBodyBones.LeftLowerArm,
        HumanBodyBones.LeftHand,
        HumanBodyBones.RightUpperArm,
        HumanBodyBones.RightLowerArm,
        HumanBodyBones.RightHand,
        HumanBodyBones.LeftUpperLeg,
        HumanBodyBones.LeftLowerLeg,
        HumanBodyBones.LeftFoot,
        HumanBodyBones.RightUpperLeg,
        HumanBodyBones.RightLowerLeg,
        HumanBodyBones.RightFoot
    };

    [Test]
    public void PlayerModel_UsesHighFidelityHumanoidImportContract()
    {
        ModelImporter importer = AssetImporter.GetAtPath(PlayerModelPath) as ModelImporter;
        Assert.IsNotNull(importer, "Player model importer is missing.");
        Assert.AreEqual(ModelImporterAnimationType.Human, importer.animationType);
        Assert.IsTrue(importer.importAnimation);
        Assert.IsTrue(importer.importBlendShapes);
        Assert.IsFalse(importer.optimizeGameObjects, "Visual driver needs exposed humanoid bones.");
        Assert.IsFalse(importer.importCameras);
        Assert.IsFalse(importer.importLights);
        Assert.IsFalse(importer.isReadable, "Readable CPU mesh data is unnecessary WebGL memory overhead.");
        Assert.AreEqual(ModelImporterMeshCompression.Off, importer.meshCompression, "Player mesh geometry should not be degraded by importer compression.");
    }

    [Test]
    public void PlayerModel_HasValidAvatarSkinnedMeshAndEssentialBones()
    {
        GameObject modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerModelPath);
        Assert.IsNotNull(modelAsset);

        GameObject instance = Object.Instantiate(modelAsset);
        try
        {
            instance.hideFlags = HideFlags.HideAndDontSave;
            SkinnedMeshRenderer[] renderers = instance.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            Assert.IsNotNull(renderers);
            Assert.Greater(renderers.Length, 0, "Player must contain at least one skinned renderer.");

            Animator animator = instance.GetComponentInChildren<Animator>(true);
            Assert.IsNotNull(animator, "Player model must contain an Animator generated by Humanoid import.");
            Assert.IsNotNull(animator.avatar);
            Assert.IsTrue(animator.avatar.isValid, "Player Avatar is invalid.");
            Assert.IsTrue(animator.avatar.isHuman, "Player Avatar is not Humanoid.");

            for (int i = 0; i < EssentialBones.Length; i++)
            {
                Assert.IsNotNull(
                    animator.GetBoneTransform(EssentialBones[i]),
                    $"Humanoid mapping is missing essential bone {EssentialBones[i]}.");
            }
        }
        finally
        {
            Object.DestroyImmediate(instance);
        }
    }

    [Test]
    public void VisualDriver_BindsProceduralPoseRigToActualHumanoidSkin()
    {
        GameObject modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerModelPath);
        Assert.IsNotNull(modelAsset);

        GameObject actor = new GameObject("PlayerHumanoidDriverTest");
        try
        {
            ProceduralHumanoidRig rig = actor.AddComponent<ProceduralHumanoidRig>();
            rig.EnsureBuilt();

            GameObject visualRootObject = new GameObject("StoreModelVisual");
            visualRootObject.transform.SetParent(actor.transform, false);
            GameObject modelInstance = Object.Instantiate(modelAsset, visualRootObject.transform);
            modelInstance.name = modelAsset.name;

            PlayerAnimationController animationController = actor.AddComponent<PlayerAnimationController>();
            Assert.IsNotNull(animationController);

            PlayerHumanoidVisualDriver driver = actor.AddComponent<PlayerHumanoidVisualDriver>();
            driver.ResolveNow();

            Assert.IsTrue(driver.IsHumanoidBound, "Actual player skin failed to bind to the procedural pose/physics rig.");
            Assert.IsNotNull(driver.VisualHead);
            Assert.IsNotNull(driver.HumanoidAnimator);

            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.Hips, out Transform hips));
            Assert.IsNotNull(hips);
            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.RightHand, out Transform rightHand));
            Assert.IsNotNull(rightHand);
            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.LeftFoot, out Transform leftFoot));
            Assert.IsNotNull(leftFoot);
        }
        finally
        {
            Object.DestroyImmediate(actor);
        }
    }

    [Test]
    public void BuildProcessor_InjectsScaledHumanoidAndAllDetailDrivers()
    {
        GameObject modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerModelPath);
        Assert.IsNotNull(modelAsset);

        GameObject actor = new GameObject("PlayerBuildInjectionTest");
        try
        {
            CharacterController controller = actor.AddComponent<CharacterController>();
            controller.height = 1.8f;
            controller.radius = 0.34f;
            controller.center = new Vector3(0f, 0.9f, 0f);
            actor.AddComponent<PlayerMover>();

            bool injected = PlayerHumanoidSceneBuildProcessor.EnsurePlayerVisualForBuild(actor, modelAsset);
            Assert.IsTrue(injected);

            Transform visualRoot = actor.transform.Find("StoreModelVisual");
            Assert.IsNotNull(visualRoot);
            Assert.Greater(visualRoot.GetComponentsInChildren<SkinnedMeshRenderer>(true).Length, 0);
            Assert.IsNotNull(actor.GetComponent<ProceduralHumanoidRig>());
            Assert.IsNotNull(actor.GetComponent<PlayerAnimationController>());
            Assert.IsNotNull(actor.GetComponent<PlayerHumanoidVisualDriver>());
            Assert.IsNotNull(actor.GetComponent<PlayerMicroMotionDetailDriver>());
            Assert.IsNotNull(actor.GetComponent<PlayerAnatomicalDetailDriver>());
            Assert.IsNotNull(actor.GetComponent<PlayerFootGroundingDetailDriver>());
            Assert.IsNotNull(actor.GetComponent<PlayerFacialMicroMotion>());

            Collider[] importedColliders = visualRoot.GetComponentsInChildren<Collider>(true);
            for (int i = 0; i < importedColliders.Length; i++)
            {
                Assert.IsFalse(importedColliders[i].enabled, "Imported character colliders must not compete with gameplay physics.");
            }

            Assert.IsTrue(TryGetRendererBounds(visualRoot, out Bounds bounds));
            Assert.That(bounds.size.y, Is.EqualTo(1.78f).Within(0.035f), "Build-injected humanoid world height drifted from the player scale contract.");
        }
        finally
        {
            Object.DestroyImmediate(actor);
        }
    }

    private static bool TryGetRendererBounds(Transform root, out Bounds bounds)
    {
        bounds = default;
        Renderer[] renderers = root.GetComponentsInChildren<Renderer>(true);
        bool hasBounds = false;
        for (int i = 0; i < renderers.Length; i++)
        {
            Renderer renderer = renderers[i];
            if (renderer == null)
            {
                continue;
            }

            if (!hasBounds)
            {
                bounds = renderer.bounds;
                hasBounds = true;
            }
            else
            {
                bounds.Encapsulate(renderer.bounds);
            }
        }

        return hasBounds;
    }
}
