using NUnit.Framework;
using UnityEditor;
using UnityEngine;

public class PlayerHumanoidIntegrationTests
{
    private const string PlayerModelPath = "Assets/Ch01_nonPBR@Double Dagger Stab.fbx";

    private static readonly HumanBodyBones[] EssentialBones =
    {
        HumanBodyBones.Hips,
        HumanBodyBones.Spine,
        HumanBodyBones.Head,
        HumanBodyBones.LeftUpperArm,
        HumanBodyBones.LeftLowerArm,
        HumanBodyBones.LeftHand,
        HumanBodyBones.RightUpperArm,
        HumanBodyBones.RightLowerArm,
        HumanBodyBones.RightHand,
        HumanBodyBones.LeftUpperLeg,
        HumanBodyBones.LeftLowerLeg,
        HumanBodyBones.LeftFoot,
        HumanBodyBones.RightUpperLeg,
        HumanBodyBones.RightLowerLeg,
        HumanBodyBones.RightFoot
    };

    [Test]
    public void PlayerModel_UsesHighFidelityHumanoidImportContract()
    {
        ModelImporter importer = AssetImporter.GetAtPath(PlayerModelPath) as ModelImporter;
        Assert.IsNotNull(importer, "Player model importer is missing.");
        Assert.AreEqual(ModelImporterAnimationType.Human, importer.animationType);
        Assert.IsTrue(importer.importAnimation);
        Assert.IsTrue(importer.importBlendShapes);
        Assert.IsFalse(importer.optimizeGameObjects, "Visual driver needs exposed humanoid bones.");
        Assert.IsFalse(importer.importCameras);
        Assert.IsFalse(importer.importLights);
        Assert.IsFalse(importer.isReadable, "Readable CPU mesh data is unnecessary WebGL memory overhead.");
        Assert.AreEqual(ModelImporterMeshCompression.Off, importer.meshCompression, "Player mesh geometry should not be degraded by importer compression.");
    }

    [Test]
    public void PlayerModel_HasValidAvatarSkinnedMeshAndEssentialBones()
    {
        GameObject modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerModelPath);
        Assert.IsNotNull(modelAsset);

        GameObject instance = Object.Instantiate(modelAsset);
        try
        {
            instance.hideFlags = HideFlags.HideAndDontSave;
            SkinnedMeshRenderer[] renderers = instance.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            Assert.IsNotNull(renderers);
            Assert.Greater(renderers.Length, 0, "Player must contain at least one skinned renderer.");

            Animator animator = instance.GetComponentInChildren<Animator>(true);
            Assert.IsNotNull(animator, "Player model must contain an Animator generated by Humanoid import.");
            Assert.IsNotNull(animator.avatar);
            Assert.IsTrue(animator.avatar.isValid, "Player Avatar is invalid.");
            Assert.IsTrue(animator.avatar.isHuman, "Player Avatar is not Humanoid.");

            for (int i = 0; i < EssentialBones.Length; i++)
            {
                Assert.IsNotNull(
                    animator.GetBoneTransform(EssentialBones[i]),
                    $"Humanoid mapping is missing essential bone {EssentialBones[i]}.");
            }
        }
        finally
        {
            Object.DestroyImmediate(instance);
        }
    }

    [Test]
    public void VisualDriver_BindsProceduralPoseRigToActualHumanoidSkin()
    {
        GameObject modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerModelPath);
        Assert.IsNotNull(modelAsset);

        GameObject actor = new GameObject("PlayerHumanoidDriverTest");
        try
        {
            ProceduralHumanoidRig rig = actor.AddComponent<ProceduralHumanoidRig>();
            rig.EnsureBuilt();

            GameObject visualRootObject = new GameObject("StoreModelVisual");
            visualRootObject.transform.SetParent(actor.transform, false);
            GameObject modelInstance = Object.Instantiate(modelAsset, visualRootObject.transform);
            modelInstance.name = modelAsset.name;

            PlayerAnimationController animationController = actor.AddComponent<PlayerAnimationController>();
            Assert.IsNotNull(animationController);

            PlayerHumanoidVisualDriver driver = actor.AddComponent<PlayerHumanoidVisualDriver>();
            driver.ResolveNow();

            Assert.IsTrue(driver.IsHumanoidBound, "Actual player skin failed to bind to the procedural pose/physics rig.");
            Assert.IsNotNull(driver.VisualHead);
            Assert.IsNotNull(driver.HumanoidAnimator);

            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.Hips, out Transform hips));
            Assert.IsNotNull(hips);
            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.RightHand, out Transform rightHand));
            Assert.IsNotNull(rightHand);
            Assert.IsTrue(driver.TryGetVisualBone(HumanBodyBones.LeftFoot, out Transform leftFoot));
            Assert.IsNotNull(leftFoot);
        }
        finally
        {
            Object.DestroyImmediate(actor);
        }
    }
}
